export const GET_PRODUTOS = 'PRODUTOS/GET_PRODUTOS'
export const ADD_PRODUTOS = 'PRODUTOS/ADD_PRODUTOS'
export const FIND_PRODUTOS = 'PRODUTOS/FIND_PRODUTOS'
export const UPDATE_PRODUTOS = 'PRODUTOS/UPDATE_PRODUTOS'
